### ISSUE TITLE
When installing CLIB2, include - somehow - a reference to which version was installed

### ISSUE THREAD

**Issue by 3246251196** [AmigaLabs/clib4#139]
When building CLIB2 and finally running "make install" it will be useful to know which version was installed. This ticket is to create a way to do that. For example, "make install" shall also copy across a file named **version.txt** to wherever it is installed to with - at least - the GIT revision.

@3246251196

**Comment by 3246251196** [comment]
It is possible to bring in the version string, "\0VER: ...." and embed it into the clib4.library. I do not see that happening at the moment. Should we consider it?

Also, is c.lib_rev.h automatically updated?

**Comment by afxgroup** [comment]
clib4 should have already $VER. did you try "version clib4.library FULL"?
c.lib_rev.h is not updated because we need bumprev for linux or something else that will update that file at every "make release" that should:
1) bump revision
2) recompile without debug
3) create release
4) optional put a release on github via api?

**Comment by 3246251196** [comment]
Okay, thanks for the info. I can see the version string.

As for your last comment, that is a good idea, but a different topic I guess. I will close this ticket now,

**Comment by 3246251196** [comment]
@afxgroup 
@walkero-gr 
I guess we can close this now?

**Comment by walkero-gr** [comment]
Yeah, I guess so.
